---
output: html_document
editor_options: 
  chunk_output_type: console
---

# DATA VISUALIZATION PROJECT - FIRST TRY

### Author: Radhika Kaul

### Date: 2/6/2020
```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r load-packages}
library(tidyverse)
```

### Preliminary data exploration

``` {r load-data}

# Loading the Quality of Government Dataset
library(readr)
Data <- read_csv("data/qog_std_cs_jan20.csv")

class(Data)  ##Determining the class the datasets belong to
```

```{r summary}
# Mean of Fragile State Index by Region across the world, but names have not transported.
Data %>%
  group_by(ht_region) %>%
  summarize(FSI_mean = mean(ffp_fsi))

```

```{r Loading_Libraries}
# Fragile States Index and Corruption Perception Index association.
# Loading necessary packages
library(tidyverse)
library(haven)
```

```{r Loading_Data}
# Loading the Quality of Government Dataset
Data_cs <- read_csv("data/qog_std_cs_jan20.csv")
Data_ts <- read_csv("data/qog_std_ts_jan20.csv")

```


```{r Plot_1_wrangling}
# Visualization 1: Correlation b/w Fragile States and Corruption Perception in the country

df_1 <- select(Data_cs, cname, ffp_fsi, ti_cpi, ht_region) 

region_df <- data.frame(ht_region = 1:10, 
                        region = c("Eastern Europe",
                                   "Latin America",
                                   "MENA",
                                   "Sub-Sharan Africa", 
                                   "Western Europe and North America",
                                   "East Asia",
                                   "South East Asia",
                                   "South Asia",
                                   "The Pacific",
                                   "The Caribbean"))

df_1_joined <- left_join(df_1, region_df, by = "ht_region")
```

```{r ggplot_1}
  ggplot(df_1_joined, mapping = aes(x = ffp_fsi, 
                                  y = ti_cpi, 
                                  color = region))+
  geom_point()+
    labs(title = paste("Relation between corruption and fragility of states across differennt \ncountries in the world in 2019 "),
         subtitle = "States with a higher fragility index are associates with higher corruption index",
         caption ="The Quality of Government Standard Dataset(2020). University of Gothenburg: The Quality of Government Institute \nFSI=0(least corrupt); FSI=100(most corrupt)\nCPI=0(most corrupt);CPI=100(least corrupt)",         
         x = "Fragile States Index",
         y = "Corruption Perceptions Index",
         color = "Region")+
    scale_x_continuous(limits=c(0,120),
                       breaks=c(0, 30, 60, 90, 120))+
    scale_y_continuous(limits=c(0,100),
                       breaks= c(0, 20, 40, 60, 80, 100))+
  theme_minimal()+
  theme(axis.title.x=element_text(hjust=+0.5),
        axis.title.y=element_text(angle=0, hjust=+1, vjust = 0.5),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title = element_text(face = "bold"),
        axis.text.x = element_text(angle = 0),
        axis.text.y = element_text(angle = 0),
        axis.line.x = element_line(linetype = "solid"),
        axis.line.y = element_line(linetype = "solid"),
        axis.ticks.x = element_line(),
        axis.ticks.y = element_line(),
        plot.margin = unit(c(1,1,1,1), "cm"))
```





```{r plot_2_wrangling}
Data_ts_new <- Data_ts %>%
               filter(cname %in% c("Afghanistan", "Pakistan", "United States", "Germany", "Iran", "Turkey", "India", "China")) %>%
               filter(year>2011) 

region_df <- data.frame(ht_region = 1:10, 
                        region = c("Eastern Europe",
                                   "Latin America",
                                   "MENA",
                                   "Sub-Sharan Africa", 
                                   "Western Europe and North America",
                                   "East Asia",
                                   "South East Asia",
                                   "South Asia",
                                   "The Pacific",
                                   "The Caribbean"))

df_2_joined <- left_join(Data_ts_new, region_df, by = "ht_region")

df_2_joined$year <- as.character(df_2_joined$year)
df_2_joined$year <- as.factor(df_2_joined$year)
df_2_joined$cname <-as.factor(df_2_joined$cname)
df_2_joined <- select(df_2_joined, cname, year, ti_cpi, ht_region, region)

```

```{r plot_2_plot}

ggplot(df_2_joined, aes(x= year , 
                  y=ti_cpi,
                  color = cname,
                  group = cname))+
  geom_path(size = 1)+
  geom_point(size = 1.5)+
  scale_color_brewer(palette = "Set1")+
  theme_minimal()+
  theme(axis.title.x=element_text(hjust=+0.5),
        axis.title.y=element_text(angle=0, hjust=+1, vjust = 0.5),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title = element_text(face = "bold"),
        axis.text.x = element_text(angle = 0),
        axis.text.y = element_text(angle = 0),
        axis.line.x = element_line(linetype = "solid"),
        axis.line.y = element_line(linetype = "solid"),
        axis.ticks.x = element_line(),
        axis.ticks.y = element_line(),
        plot.margin = unit(c(0.5,0.5,0.5,0.5), "cm"))+
  labs(title = paste("CPI|Corruption Perception Index for selected countries between years 2010-2019 "),
       subtitle = "The CPI generally defines corruption as the misuse of public power for private benefit.\nThe CPI currently ranks 176 countrieson a scale of 100(very clean) to 0(highly corrupt)",
       caption ="Source:The Quality of Government Standard Dataset(2020). University of Gothenburg: The Quality of Government Institute",
       fill = "Country",
       x = "Year",
       y = "Corruption Perception Index ")
```

